---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7-chef-11
    driver:
      box: opscode-centos-6.7
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
    provisioner:
      require_chef_omnibus: 11.18.6
  - name: centos-6.7-chef-latest
    driver:
      box: opscode-centos-6.7
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
    provisioner:
      require_chef_omnibus: latest
  - name: centos-7.0-chef-latest
    driver:
      box: opscode-centos-7.0
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box
    provisioner:
      require_chef_omnibus: latest

suites:
  - name: default
    run_list:
      - recipe[selinux::enforcing]
      - recipe[selinux_policy_test::setup]
      - recipe[selinux_policy_test::single_port]
      - recipe[selinux_policy_test::twice_port]
      - recipe[selinux_policy_test::range_port]
      - recipe[selinux_policy_test::module]
      - recipe[selinux_policy_test::module_directory]
      - recipe[selinux_policy_test::fcontext]
    attributes:
